In [28]:
import quandl
import pandas as pd
import numpy as np

## Daily Bitcoin Stats Summary

These are the properties we will be using for the price prediction

* MWNUS -> Bitcoin My Wallet Number of Users
* MKPRU -> Bitcoin Market Price USD
* TRVOU -> Bitcoin USD Exchange Trade Volume
* DIFF -> Bitcoin Difficulty
* MWNTD -> Bitcoin My Wallet Number of Transactions Per Day
* MWTRV -> My Wallet Transaction Volume
* AVBLS -> Bitcoin Average Block Size
* BLCHS -> Bitcoin api.blockchain Size
* MIREV -> Bitcoin Miners Revenue
* HRATE -> Bitcoin Hash Rate
* CPTRA -> Bitcoin Cost per Transaction
* CPTRV -> Bitcoin Cost % of Transaction Volume
* ETRVU -> Bitcoin Estimated Transaction Volume USD
* TOUTV -> Bitcoin Total Output Volume
* NTRBL -> Bitcoin Number of Transaction per Block
* NADDU -> Bitcoin Number of Unique Bitcoin Addresses Used
* NTRAT -> Bitcoin Total Number of Transactions
* NTRAN -> Bitcoin Number of Transactions
* TRFUS -> Bitcoin Total Transaction Fees USD
* MKTCP -> Bitcoin Market Capitalization
* TOTBC -> Total Bitcoins

In [29]:
blockchain_props = ['MWNUS', 'MKPRU', 'TRVOU', 'DIFF', 'MWNTD', 'MWTRV', 'AVBLS', 'BLCHS', 'MIREV', \
                    'HRATE', 'CPTRA', 'CPTRV', 'ETRVU', 'TOUTV', 'NTRBL', 'NADDU', 'NTRAT', 'NTRAN', \
                    'TRFUS', 'MKTCP', 'TOTBC']

data = None

for prop in blockchain_props:
    bc_prop = 'BCHAIN/' + prop
    if data is None:
        data = quandl.get(bc_prop)
    else:
        data = pd.merge(data, quandl.get(bc_prop), on='Date')

data.columns = blockchain_props
data.tail()

BCHAIN/MWNUS
BCHAIN/MKPRU
BCHAIN/TRVOU
BCHAIN/DIFF
BCHAIN/MWNTD
BCHAIN/MWTRV
BCHAIN/AVBLS
BCHAIN/BLCHS
BCHAIN/MIREV
BCHAIN/HRATE
BCHAIN/CPTRA
BCHAIN/CPTRV
BCHAIN/ETRVU
BCHAIN/TOUTV
BCHAIN/NTRBL
BCHAIN/NADDU
BCHAIN/NTRAT
BCHAIN/NTRAN
BCHAIN/TRFUS
BCHAIN/MKTCP
BCHAIN/TOTBC

,Value_x,Value_y,Value_x,Value_y,Value_x,Value_y,Value_x,Value_y,Value_x,Value_y,...,Value_y,Value_x,Value_y,Value_x,Value_y,Value_x,Value_y,Value_x,Value_y,Value
Date,,,,,,,,,,,,,,,,,,,,,
2009-01-04,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,50.0
2009-01-05,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,50.0
2009-01-06,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,50.0
2009-01-07,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,50.0
2009-01-08,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,50.0

In [26]:
data.count()

MWNUS    3967
MKPRU    3967
TRVOU    3967
DIFF     3967
MWNTD    3967
MWTRV    3967
AVBLS    3967
BLCHS    3967
MIREV    3967
HRATE    3967
CPTRA    3967
CPTRV    3967
ETRVU    3967
TOUTV    3967
NTRBL    3967
NADDU    3967
NTRAT    3967
NTRAN    3967
TRFUS    3967
MKTCP    3967
TOTBC    3967
dtype: int64